
version: '2'

services:
  node:
    build: .
    container_name: nodeMine
    image: blog
    volumes:
      - .:/mine
      - /mine/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
  
  nginx:
    restart: always
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - node
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx/:/etc/nginx/conf.d
      - ./log:/var/log/nginx
      - ./:/mine
      - ./config/crt/:/etc/letsencrypt
      - .:/mine
      
  db:
    image: mongo
    container_name: mineD
    ports:
      - "27017:27017"
    command: "--smallfiles --logpath=/dev/null"